/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author you have to better
 */
public class ManHinhQuanLyPhong extends javax.swing.JFrame {

    public static int soTang;
    public static int soPhong;
    public static int RoomMap[][];

    public ManHinhQuanLyPhong() {
        initComponents();
        setTitle("Quan ly phong khach san");
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jpnAreaRoomMap = new javax.swing.JPanel();
        jButton41 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpnAreaRoomMapLayout = new javax.swing.GroupLayout(jpnAreaRoomMap);
        jpnAreaRoomMap.setLayout(jpnAreaRoomMapLayout);
        jpnAreaRoomMapLayout.setHorizontalGroup(
            jpnAreaRoomMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jpnAreaRoomMapLayout.setVerticalGroup(
            jpnAreaRoomMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jpnAreaRoomMap);

        jButton41.setText("Tao So Do Phong");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton1.setText("TaoPhong");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton41)
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton41)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        multi_input();
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createFloor(6, 7);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void init() {
        soPhong = 0;
        soTang = 0;
    }

    /**
     *
     */
    public void multi_input() {
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("soTang:"));
        myPanel.add(xField);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("soPhong:"));
        myPanel.add(yField);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Please Enter X and Y Values", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            soPhong = Integer.parseInt(yField.getText());
            soTang = Integer.parseInt(xField.getText());
            System.out.println("x value: " + xField.getText());
            System.out.println("y value: " + yField.getText());
        }
    }

    public void createFloor(int floors, int rooms) {
        
        
        GridBagLayout layout = new GridBagLayout();
        jpnAreaRoomMap.setLayout(layout);
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        jpnAreaRoomMap.add(new JLabel("Tang 1"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 0;
        jpnAreaRoomMap.add(new JToolBar("TAng 1 ne"), gbc);
        
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        jpnAreaRoomMap.add(new JLabel("Tang 2"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 0;
        jpnAreaRoomMap.add(new JToolBar("TAng 2 ne"), gbc);
        
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 1;
        jpnAreaRoomMap.add(new JLabel("Tang 3"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 1;
        jpnAreaRoomMap.add(new JToolBar("TAng 3 ne"), gbc);
        
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 2;
        jpnAreaRoomMap.add(new JLabel("Tang 4"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 2;
        jpnAreaRoomMap.add(new JToolBar("TAng 4 ne"), gbc);
        
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 3;
        jpnAreaRoomMap.add(new JLabel("Tang 5"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 3;
        jpnAreaRoomMap.add(new JToolBar("TAng 5 ne"), gbc);
        
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 4;
        jpnAreaRoomMap.add(new JLabel("Tang 6"), gbc);
        gbc.gridx = 1;
        gbc.gridy = 4;
        jpnAreaRoomMap.add(new JToolBar("TAng 6 ne"), gbc);
        
//        JLabel title1 = new JLabel();
//        title1.setText("Floor 1");
//        title1.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title1);
//        JToolBar tang1 = new JToolBar();
//        jpnAreaRoomMap.add(tang1);
//        //---------------------
//        JLabel title2 = new JLabel();
//        title2.setText("Floor 2");
//        title2.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title2);
//        JToolBar tang2 = new JToolBar();
//        jpnAreaRoomMap.add(tang2);
//        //---------------------
//        JLabel title3 = new JLabel();
//        title3.setText("Floor 3");
//        title3.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title3);
//        JToolBar tang3 = new JToolBar();
//        jpnAreaRoomMap.add(tang3);
//        //---------------------
//        JLabel title4 = new JLabel();
//        title4.setText("Floor 4");
//        title4.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title4);
//        JToolBar tang4 = new JToolBar();
//        jpnAreaRoomMap.add(tang4);
//        //---------------------
//        JLabel title5 = new JLabel();
//        title5.setText("Floor 5");
//        title5.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title5);
//        JToolBar tang5 = new JToolBar();
//        jpnAreaRoomMap.add(tang5);
//        //---------------------
//        JLabel title6 = new JLabel();
//        title6.setText("Floor 6");
//        title6.setPreferredSize(new Dimension(100, 100));
//        jpnAreaRoomMap.add(title6);
//        JToolBar tang6 = new JToolBar();
//        jpnAreaRoomMap.add(tang6);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnAreaRoomMap;
    // End of variables declaration//GEN-END:variables
}
